services:
  api:
    ports: []
    image: ghcr.io/citenbox/bookscrude-api:prod
  web:
    build: 
      context: ./client
      dockerfile: Dockerfile.nginx
    image: ghcr.io/citenbox/bookscrude-web:prod
    ports: ["8080:80"]
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://127.0.0.1/api/health >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    