services:
  api:
    build: ./server
    environment:
      - PORT=3001
    healthcheck:
      test: ["CMD", "curl", "-fsS", "localhost:3001/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped