services:
  api:
    ports: ["3001:3001"]

  web:
    build: 
      context: ./client
    environment:
      - VITE_API_BASE_URL=http://localhost:3001
    ports: ["5173:5173"]
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      api:
        condition: service_healthy